# remotes::install_github("10XGenomics/loupeR")
rm(list=ls())
library(loupeR)
library(Seurat)
seuset = readRDS('/lvdata/wzb/scRNA/FW2023-660/h5_trans.rds')
setwd('/lvdata/wzb/scRNA/FW2023-660/')
# install.packages("/home/wzb/pkg/loupeR_Linux.tar.gz", repos = NULL, type = "source")
# loupeR::setup()
create_loupe_from_seurat(seuset,output_dir ='/lvdata/wzb/scRNA/FW2023-660/')